version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt
    - requirements: docs/torch_requirements.txt

sphinx:
  configuration: docs/source/conf.py
